# Linear Algebra

## Motivation

We begin by examining the objects of linear algebra, namely scalars, vectors, matrices, and tensors, along with their properties. These object underly much of scientific computing and in particular deep learning modeling.



## Scalars

**Scalars** - We call values consisting of just one numerical quantity *scalars*.

For example 0, 1, and 3.14159 are scalars.

Scalar variables are denoted by ordinary lower-cased letters (e.g., $x$, $y$, and $z$).

The space of all (continuous) *real-valued* scalars is denoted by $\mathbb{R}$

$x \in \mathbb{R}$ is a formal way to say that $x$ is a real-valued scalar.

A scalar is represented by a tensor with just one element.

In [1]:
# binary operations on scalars
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## Vectors

**Vectors** - You can think of a vector as simply a list of scalar values.

In math notation, we will usually denote vectors as bold-faced,
lower-cased letters (e.g., $\mathbf{x}$, $\mathbf{y}$, and $\mathbf{z})$.

We work with vectors via one-dimensional tensors.

In [2]:
# sample vector
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

## Indexing

We can refer to any element of a vector by using a subscript. For example, we can refer to the $i^\mathrm{th}$ element of $\mathbf{x}$ by $x_i$, where $x_i$ is a scalar.

In math, a vector $\mathbf{x}$ can be written as

$$\mathbf{x} =\begin{bmatrix}x_{1}  \\x_{2}  \\ \vdots  \\x_{n}\end{bmatrix},$$

where $x_1, \ldots, x_n$ are elements of the vector.

In [3]:
# index into a vector
x[3]

tensor(3)

### Length, Dimensionality, and Shape

In math notation, if we want to say that a vector $\mathbf{x}$
consists of $n$ real-valued scalars, we can express this as $\mathbf{x} \in \mathbb{R}^n$.

The length of a vector is commonly called the *dimension* of the vector.


In [4]:
# access with builtin python len() function
len(x)

4

In [5]:
# We can also access its length via the `.shape` attribute.
x.shape

torch.Size([4])

Note that the word "dimension" tends to get overloaded in these contexts and this tends to confuse people.

To clarify, we use the dimensionality of a *vector* or an *axis*
to refer to its length, i.e., the number of elements of a vector or an axis.

However, we use the dimensionality of a tensor to refer to the number of axes that a tensor has. In this sense, the dimensionality of some axis of a tensor will be the length of that axis.

For example, the dimensionality of the following is 3.
$$\mathbf{x} =\begin{bmatrix}x_{1}  \\x_{2}  \\x_{3}\end{bmatrix},$$

But the dimensionality of the following is 2.

$$\mathbf{A}=\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \\ \end{bmatrix}.$$

## Matrices

**Matrices** - A matrix is a collection of vectors in $\mathbb{R}^n$

Matrices, are typically denoted with bold-faced, capital letters
(e.g., $\mathbf{X}$, $\mathbf{Y}$, and $\mathbf{Z}$).

In math notation, we use $\mathbf{A} \in \mathbb{R}^{m \times n}$
to express that the matrix $\mathbf{A}$ consists of $m$ rows and $n$ columns of real-valued scalars.
Visually, we can illustrate any matrix $\mathbf{A} \in \mathbb{R}^{m \times n}$ as a table,
where each element $a_{ij}$ belongs to the $i^{\mathrm{th}}$ row and $j^{\mathrm{th}}$ column:

$$\mathbf{A}=\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \\ \end{bmatrix}.$$

For any $\mathbf{A} \in \mathbb{R}^{m \times n}$, the shape of $\mathbf{A}$ is ($m$, $n$) or $m \times n$.

Specifically, when a matrix has the same number of rows and columns,
its shape becomes a square; thus, it is called a **square matrix**.

In [6]:
# example matrix
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

## Indexing Matrices
We can access the scalar element $a_{ij}$ of a matrix $\mathbf{A}$ by specifying the indices for the row ($i$) and column ($j$), such as $[\mathbf{A}]_{ij}$.

When the scalar elements of a matrix $\mathbf{A}$ are not given, we may simply use the lower-case letter of the matrix $\mathbf{A}$ with the index subscript, $a_{ij}$, to refer to $[\mathbf{A}]_{ij}$.

When we exchange a matrix's rows and columns, the result is called the **transpose** of the matrix.

Formally, we signify a matrix $\mathbf{A}$'s transpose by $\mathbf{A}^\top$ and if $\mathbf{B} = \mathbf{A}^\top$, then $b_{ij} = a_{ji}$ for any $i$ and $j$. Thus, the transpose of $\mathbf{A}$ is a $n \times m$ matrix:

$$
\mathbf{A}^\top =
\begin{bmatrix}
    a_{11} & a_{21} & \dots  & a_{m1} \\
    a_{12} & a_{22} & \dots  & a_{m2} \\
    \vdots & \vdots & \ddots  & \vdots \\
    a_{1n} & a_{2n} & \dots  & a_{mn}
\end{bmatrix}.
$$

**Understanding check:** What's the intuitive way to describe the transpose? 

In [7]:
# transpose in code
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

As a special type of the square matrix, a **symmetric matrix** $\mathbf{A}$ is equal to its transpose: $\mathbf{A} = \mathbf{A}^\top$.


In [8]:
# a symmetric matrix B.
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

Now we compare `B` with its transpose.


In [9]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Matrices are useful for machine learning!
For example, rows in our matrix might correspond to different examples (e.g. houses), while columns might correspond to different attributes (e.g. price, number of bedrooms, etc.).

## Tensors

**Tensors** - ("tensors" in this subsection refer to algebraic objects) give us a generic way of describing $n$-dimensional arrays with an arbitrary number of axes.

Tensors are denoted with capital letters of a special font face (e.g., $\mathsf{X}$, $\mathsf{Y}$, and $\mathsf{Z}$) and their indexing mechanism (e.g., $x_{ijk}$ and $[\mathsf{X}]_{1, 2i-1, 3}$) is similar to that of matrices.

**NB:** vectors are first-order tensors and matrices are second-order tensors.

In [10]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Tensors are important data structures for all sorts of data such as images, which have 3 axes corresponding to the height, width, and a *channel* for stacking the color channels (red, green, and blue).

## Basic Properties of Tensor Arithmetic

Unary operations and elementwise binary operations maintain the shape of the tensor.

In [11]:
# elementwise binary operation
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # Assign a copy of `A` to `B` by allocating new memory
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

Specifically, elementwise multiplication of two matrices is called their *Hadamard product* (math notation $\odot$).
Consider matrix $\mathbf{B} \in \mathbb{R}^{m \times n}$ whose element of row $i$ and column $j$ is $b_{ij}$. The Hadamard product of matrices $\mathbf{A}$ and $\mathbf{B}$ is:

$$
\mathbf{A} \odot \mathbf{B} =
\begin{bmatrix}
    a_{11}  b_{11} & a_{12}  b_{12} & \dots  & a_{1n}  b_{1n} \\
    a_{21}  b_{21} & a_{22}  b_{22} & \dots  & a_{2n}  b_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1}  b_{m1} & a_{m2}  b_{m2} & \dots  & a_{mn}  b_{mn}
\end{bmatrix}.
$$


In [12]:
# elementwise multiplication (aka Hadamard product)
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

Multiplying or adding a tensor by a scalar also does not change the shape of the tensor, where each element of the operand tensor will be added or multiplied by the scalar.

In [13]:
# matrix-scalar multiplication
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X, a + X, (a * X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## Reduction

One useful operation that we can perform with arbitrary tensors is to calculate the sum of their elements.

In mathematical notation, we express sums using the $\sum$ symbol. To express the sum of the elements in a vector $\mathbf{x}$ of length $d$, we write $\sum_{i=1}^d x_i$.

In [14]:
# sum
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

We can express sums over the elements of tensors of arbitrary shape.

For example, the sum of the elements of an $m \times n$ matrix $\mathbf{A}$ could be written $\sum_{i=1}^{m} \sum_{j=1}^{n} a_{ij}$.


In [15]:
# matrix sum
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

By default, invoking the function for calculating the sum *reduces* a tensor along all its axes to a scalar.

To reduce the row dimension (axis 0) by summing up elements of all the rows, we specify `axis=0` when invoking the function.

In [16]:
A_sum_axis0 = A.sum(axis=0)
A, A_sum_axis0, A_sum_axis0.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 torch.Size([4]))

Specifying `axis=1` will reduce the column dimension (axis 1) by summing up elements of all the columns.
Thus, the dimension of axis 1 of the input is lost in the output shape.


In [17]:
A_sum_axis1 = A.sum(axis=1)
A, A_sum_axis1, A_sum_axis1.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]))

Reducing a matrix along both rows and columns via summation
is equivalent to summing up all the elements of the matrix.


In [18]:
A.sum(axis=[0, 1])  # Same as `A.sum()`

tensor(190.)

A related quantity is the **mean**, which is also called the **average**. We calculate the mean by dividing the sum by the total number of elements.

In [19]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

Likewise, the function for calculating the mean can also reduce a tensor along the specified axes.


In [20]:
A, A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([ 8.,  9., 10., 11.]))

### Non-Reduction Sum
However, sometimes it can be useful to keep the number of axes unchanged
when invoking the function for calculating the sum or mean.

In [21]:
sum_A = A.sum(axis=1, keepdims=True)
A, sum_A, A.shape, sum_A.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 4]),
 torch.Size([5, 1]))

For instance, since `sum_A` still keeps its two axes after summing each row, we can divide `A` by `sum_A` with broadcasting.


In [22]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

If we want to calculate the cumulative sum of elements of `A` along some axis, say `axis=1` (col by col),
we can call the `cumsum` function. This function will not reduce the input tensor along any axis.

In [23]:
A,A.cumsum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  3.,  6.],
         [ 4.,  9., 15., 22.],
         [ 8., 17., 27., 38.],
         [12., 25., 39., 54.],
         [16., 33., 51., 70.]]))

## Dot Products

**Dot product** - Given two vectors $\mathbf{x}, \mathbf{y} \in \mathbb{R}^d$, their **dot product** $\mathbf{x}^\top \mathbf{y}$ (or $\langle \mathbf{x}, \mathbf{y}  \rangle$) is a sum over the products of the elements at the same position: $\mathbf{x}^\top \mathbf{y} = \sum_{i=1}^{d} x_i y_i$.

**Understanding check:** Why do we take the transpose of vector $\mathbf{x}$?

In [24]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

Note that we can express the dot product of two vectors equivalently by performing an elementwise multiplication and then a sum:


In [25]:
torch.sum(x * y)

tensor(6.)

Dot products are useful in a wide range of contexts. For example, given some set of values,
denoted by a vector $\mathbf{x}  \in \mathbb{R}^d$ and a set of weights denoted by $\mathbf{w} \in \mathbb{R}^d$,
the weighted sum of the values in $\mathbf{x}$ according to the weights $\mathbf{w}$ could be expressed as the dot product $\mathbf{x}^\top \mathbf{w}$.

## Matrix-Vector Products

**Matrix-vector products** - Recall the matrix $\mathbf{A} \in \mathbb{R}^{m \times n}$
and the vector $\mathbf{x} \in \mathbb{R}^n$. The matrix-vector product $\mathbf{A}\mathbf{x}$
is simply a column vector of length $m$, whose $i^\mathrm{th}$ element is the dot product $\mathbf{a}^\top_i \mathbf{x}$

To make this more clear let us visualize the matrix $\mathbf{A}$ in terms of its row vectors:

$$\mathbf{A}=
\begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix},$$

where each $\mathbf{a}^\top_{i} \in \mathbb{R}^n$ is a row vector representing the $i^\mathrm{th}$ row of the matrix $\mathbf{A}$.

Now the matrix-vector product $\mathbf{A}\mathbf{x}$ is represented as:

$$
\mathbf{A}\mathbf{x}
= \begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix}\mathbf{x}
= \begin{bmatrix}
 \mathbf{a}^\top_{1} \mathbf{x}  \\
 \mathbf{a}^\top_{2} \mathbf{x} \\
\vdots\\
 \mathbf{a}^\top_{m} \mathbf{x}\\
\end{bmatrix}.
$$

We can think of multiplication by a matrix $\mathbf{A}\in \mathbb{R}^{m \times n}$
as a transformation that projects vectors
from $\mathbb{R}^{n}$ to $\mathbb{R}^{m}$.

Matrix-vector products are heavily used in a neural networks.

In [26]:
A, x

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]))

In [27]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

**Understanding check:** What's the difference between `torch.mv` and `torch.mm`?

In [28]:
A, x.unsqueeze(-1), A.shape, x.unsqueeze(-1).shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[0.],
         [1.],
         [2.],
         [3.]]),
 torch.Size([5, 4]),
 torch.Size([4, 1]))

In [29]:
# throws error because x is no longer a vector
# torch.mv(A, x.unsqueeze(-1))

In [30]:
# but this works
torch.mm(A, x.unsqueeze(-1))

tensor([[ 14.],
        [ 38.],
        [ 62.],
        [ 86.],
        [110.]])

## Matrix-Matrix Multiplication

**Matrix-matrix multiplication** - Say that we have two matrices $\mathbf{A} \in \mathbb{R}^{n \times k}$ and $\mathbf{B} \in \mathbb{R}^{k \times m}$ and their matrix product is denoted $\mathbf{C} = \mathbf{A}\mathbf{B}$ then the matrix product $\mathbf{C} \in \mathbb{R}^{n \times m}$ contains elements $c_{ij}$ as the dot product $\mathbf{a}^\top_i \mathbf{b}_j$.

$$\mathbf{A}=\begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1k} \\
 a_{21} & a_{22} & \cdots & a_{2k} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nk} \\
\end{bmatrix},\quad
\mathbf{B}=\begin{bmatrix}
 b_{11} & b_{12} & \cdots & b_{1m} \\
 b_{21} & b_{22} & \cdots & b_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
 b_{k1} & b_{k2} & \cdots & b_{km} \\
\end{bmatrix}.$$


Denote by $\mathbf{a}^\top_{i} \in \mathbb{R}^k$
the row vector representing the $i^\mathrm{th}$ row of the matrix $\mathbf{A}$,
and let $\mathbf{b}_{j} \in \mathbb{R}^k$
be the column vector from the $j^\mathrm{th}$ column of the matrix $\mathbf{B}$.
To produce the matrix product $\mathbf{C} = \mathbf{A}\mathbf{B}$, it is easiest to think of $\mathbf{A}$ in terms of its row vectors and $\mathbf{B}$ in terms of its column vectors:

$$\mathbf{A}=
\begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_n \\
\end{bmatrix},
\quad \mathbf{B}=\begin{bmatrix}
 \mathbf{b}_{1} & \mathbf{b}_{2} & \cdots & \mathbf{b}_{m} \\
\end{bmatrix}.
$$




$$\mathbf{C} = \mathbf{AB} = \begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_n \\
\end{bmatrix}
\begin{bmatrix}
 \mathbf{b}_{1} & \mathbf{b}_{2} & \cdots & \mathbf{b}_{m} \\
\end{bmatrix}
= \begin{bmatrix}
\mathbf{a}^\top_{1} \mathbf{b}_1 & \mathbf{a}^\top_{1}\mathbf{b}_2& \cdots & \mathbf{a}^\top_{1} \mathbf{b}_m \\
 \mathbf{a}^\top_{2}\mathbf{b}_1 & \mathbf{a}^\top_{2} \mathbf{b}_2 & \cdots & \mathbf{a}^\top_{2} \mathbf{b}_m \\
 \vdots & \vdots & \ddots &\vdots\\
\mathbf{a}^\top_{n} \mathbf{b}_1 & \mathbf{a}^\top_{n}\mathbf{b}_2& \cdots& \mathbf{a}^\top_{n} \mathbf{b}_m
\end{bmatrix}.
$$

We can think of the matrix-matrix multiplication $\mathbf{AB}$ as simply performing $m$ matrix-vector products and stitching the results together to form an $n \times m$ matrix.

In [31]:
# example
B = torch.ones(4, 3)
A, B, torch.mm(A, B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

Matrix-matrix multiplication can be simply called *matrix multiplication*, and should not be confused with the Hadamard product.

**Understanding check:** What's the difference between `torch.mm` and `torch.matmul`?

In [32]:
A, B.unsqueeze(-1), A.shape, B.unsqueeze(-1).shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[[1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.]]]),
 torch.Size([5, 4]),
 torch.Size([4, 3, 1]))

In [33]:
# throws error because x is no longer a vector
# torch.mm(A, B.unsqueeze(-1))

In [34]:
# matmul works for higher-dimension tensors
A.unsqueeze(1).shape, B.shape, torch.matmul(A.unsqueeze(1), B), torch.matmul(A.unsqueeze(1), B).shape 

(torch.Size([5, 1, 4]),
 torch.Size([4, 3]),
 tensor([[[ 6.,  6.,  6.]],
 
         [[22., 22., 22.]],
 
         [[38., 38., 38.]],
 
         [[54., 54., 54.]],
 
         [[70., 70., 70.]]]),
 torch.Size([5, 1, 3]))

## Norms

**Norm** - Informally, the norm of a vector tells us how *big* a vector is.

The notion of *size* under consideration here concerns not dimensionality but rather the magnitude of the components.

In linear algebra, a vector norm is a function $f$ that maps a vector to a scalar, satisfying a handful of properties.

Given any vector $\mathbf{x}$, the first property says that if we scale all the elements of a vector
by a constant factor $\alpha$, its norm also scales by the *absolute value* of the same constant factor:

$$f(\alpha \mathbf{x}) = |\alpha| f(\mathbf{x}).$$


The second property is the familiar triangle inequality:

$$f(\mathbf{x} + \mathbf{y}) \leq f(\mathbf{x}) + f(\mathbf{y}).$$


The third property simply says that the norm must be non-negative:

$$f(\mathbf{x}) \geq 0.$$

The final property requires that the smallest norm is achieved and only achieved
by a vector consisting of all zeros.

$$\forall i, [\mathbf{x}]_i = 0 \Leftrightarrow f(\mathbf{x})=0.$$

The Euclidean distance is a norm: specifically it is the $L_2$ norm.

Suppose that the elements in the $n$-dimensional vector
$\mathbf{x}$ are $x_1, \ldots, x_n$.
The $L_2$ *norm* of $\mathbf{x}$ is the square root of the sum of the squares of the vector elements:

$$\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2},$$

where the subscript $2$ is often omitted in $L_2$ norms, i.e., $\|\mathbf{x}\|$ is equivalent to $\|\mathbf{x}\|_2$. 

In [35]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In deep learning, we work more often
with the squared $L_2$ norm.
You will also frequently encounter the $L_1$ *norm*,
which is expressed as the sum of the absolute values of the vector elements:

$$\|\mathbf{x}\|_1 = \sum_{i=1}^n \left|x_i \right|.$$

As compared with the $L_2$ norm,
it is less influenced by outliers.
To calculate the $L_1$ norm, we compose
the absolute value function with a sum over the elements.


In [36]:
torch.abs(u).sum()

tensor(7.)

Both the $L_2$ norm and the $L_1$ norm
are special cases of the more general $L_p$ *norm*:

$$\|\mathbf{x}\|_p = \left(\sum_{i=1}^n \left|x_i \right|^p \right)^{1/p}.$$

Analogous to $L_2$ norms of vectors,
the *Frobenius norm* of a matrix $\mathbf{X} \in \mathbb{R}^{m \times n}$
is the square root of the sum of the squares of the matrix elements:

$$\|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}.$$

The Frobenius norm satisfies all the properties of vector norms.
It behaves as if it were an $L_2$ norm of a matrix-shaped vector.
Invoking the following function will calculate the Frobenius norm of a matrix.


In [37]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

### Norms and Objectives
In deep learning, we are often trying to solve optimization problems such as *minimizing* the distance between predictions and the ground-truth observations.

Oftentimes, the objectives, perhaps the most important components of deep learning algorithms (besides the data), are expressed as norms.

## Exercises

1. Prove that the transpose of a matrix $\mathbf{A}$'s transpose is $\mathbf{A}$: $(\mathbf{A}^\top)^\top = \mathbf{A}$.
1. Given two matrices $\mathbf{A}$ and $\mathbf{B}$, show that the sum of transposes is equal to the transpose of a sum: $\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top$.
1. Given any square matrix $\mathbf{A}$, is $\mathbf{A} + \mathbf{A}^\top$ always symmetric? Why?
1. We defined the tensor `X` of shape (2, 3, 4) in this section. What is the output of `len(X)`?
1. For a tensor `X` of arbitrary shape, does `len(X)` always correspond to the length of a certain axis of `X`? What is that axis?
1. Run `A / A.sum(axis=1)` and see what happens. Can you analyze the reason?
1. When traveling between two points in Manhattan, what is the distance that you need to cover in terms of the coordinates, i.e., in terms of avenues and streets? Can you travel diagonally?
1. Consider a tensor with shape (2, 3, 4). What are the shapes of the summation outputs along axis 0, 1, and 2?
1. Feed a tensor with 3 or more axes to the `linalg.norm` function and observe its output. What does this function compute for tensors of arbitrary shape?

## Bonus exercise
1. Prove that the $L_2$ function satisfies the norm properties.

## Exercise solutions

1) Prove that the transpose of a matrix $\mathbf{A}$'s transpose is $\mathbf{A}$: $(\mathbf{A}^\top)^\top = \mathbf{A}$.

**Intuition:** refer to the definition of a transpose and check that the claim holds. Big idea: double transpose returns the same result.

Let $A' = A^\top$, which implies $a'_{ij} = a_{ji}$ by the definition of the transpose. Further, let $A'' = A'^\top$, which implies $a''_{ji} = a'_{ij}$. But this means that $a_{ji} = a'_{ij} = a''_{ji}$, which means all the elements of $A = (\mathbf{A}^\top)^\top$, which shows that the claim holds.

2) Given two matrices $\mathbf{A}$ and $\mathbf{B}$, show that the sum of transposes is equal to the transpose of a sum: $\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top$.

**Intuition:** refer to the definition of a transpose and check that the relation holds. Big idea: transpose distributes.

Let $A' = A^\top$, which implies $a'_{ij} = a_{ji}$ by the definition of the transpose. Further, let $B' = B^\top$, which implies $b'_{ij} = b_{ji}$.

Now let $C = \mathbf{A}^\top + \mathbf{B}^\top$, which implies that $c_{ij} = a'_{ij} + b'_{ij} = a_{ji} + b_{ji}$.

Let $C' = (\mathbf{A} + \mathbf{B})^\top$, which implies $c'_{ij} = a_{ji} + b_{ji}$.

But this means that $c_{ij} = a_{ji} + b_{ji} = c'_{ij}$, which means all the elements of $C = C'$, which shows that the claim holds.

3) Given any square matrix $\mathbf{A}$, is $\mathbf{A} + \mathbf{A}^\top$ always symmetric? Why?

**Intuition:** Refer to the definition of symmetric and determine if the claim holds. Try translating the definition into the context of this problem as follows: $(\mathbf{A} + \mathbf{A}^\top)^\top \stackrel{?}{=}\mathbf{A} + \mathbf{A}^\top$. Another way of thinking about this is to build on the tools from 1) and 2).

**Approach one:**

Suppose $\mathbf{A} \in \mathbb{R}^{n \times n}$. Let $\mathbf{B} = \mathbf{A} + \mathbf{A}^\top$, which implies $b_{ij} = a_{ij} + a_{ji}$. Further, let $\mathbf{B}' = \mathbf{B}^\top$, which implies $b'_{ij} = b_{ji}$. We now show that $b'_{ij} = b_{ij}$. $b'_{ij} = b_{ji} = a_{ji} + a_{ij}$ and $b_{ij} = a_{ij} + a_{ji}$, which shows that that $b'_{ij} = a_{ji} + a_{ij} = a_{ij} + a_{ji} = b_{ij}$ by commutativity of addition.

From this we conclude that all element of $\mathbf{B} = \mathbf{B}^\top$ and claim holds.

**Approach two:**

We know by problem 1) and 2) that $(\mathbf{A} + \mathbf{A}^\top)^\top = \mathbf{A}^\top + (\mathbf{A}^\top)^\top = \mathbf{A}^\top + \mathbf{A}$, which shows that the claim holds.

**Example:**
$\mathbf{A} + \mathbf{A}^\top = \mathbf{A'}$ is symmetric. This is because we're pairing numbers across the diagonal and addition is commutative. This wouldn't hold if the matrix was not square because you wouldn't be able to pair all elements of the matrix across the diagonal.

In [38]:
# example supporting problem 3
A = torch.tensor([[1, 2, 3], 
                  [4, 5, 6],
                  [7, 8, 9]])
B = A + A.T
(B.T == B).all()

tensor(True)

In [39]:
# 4)
X = torch.arange(24).reshape(2,3,4)
len(X)

2

5) Yes - the first dimension (i.e. the zeroth dimension)

In [40]:
# 6) The issue with A / A.sum(axis=1) is that we are dividing a matrix with 4 columns by 5 values (the reduced sum). 
# This can be fixed by summing row-wise (i.e. A.sum(axis=0)) and dividing so that the dimensions align. 
# This is due to broadcasting semantics. https://pytorch.org/docs/stable/notes/broadcasting.html
A = torch.arange(20).reshape(5, 4)
A / A.sum(axis=0)

tensor([[0.0000, 0.0222, 0.0400, 0.0545],
        [0.1000, 0.1111, 0.1200, 0.1273],
        [0.2000, 0.2000, 0.2000, 0.2000],
        [0.3000, 0.2889, 0.2800, 0.2727],
        [0.4000, 0.3778, 0.3600, 0.3455]])

7) This is the $L_1$ norm (aka the Manhattan distance).

In [41]:
# 8) try drawing this out to visualize the changes!
X = torch.arange(24).reshape(2,3,4)
X.sum(axis=0).shape, X.sum(axis=1).shape, X.sum(axis=2).shape, 

(torch.Size([3, 4]), torch.Size([2, 4]), torch.Size([2, 3]))

In [42]:
# 9) This computes a generalized Frobenius norm and takes the $L_2$ norm of all elements in the tensor.
X = torch.arange(24, dtype=float).reshape(2, 3, 4)
result = torch.norm(X)

# sanity check
squared_sums = 0
for i in range(24):
    squared_sums += i**2
check = squared_sums**.5

result, check

(tensor(65.7571, dtype=torch.float64), 65.75712889109438)